/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminSettings = IDL.Record({
  'aiMode' : IDL.Bool,
  'aiVoice' : IDL.Bool,
});
export const SenderType = IDL.Variant({
  'ai' : IDL.Null,
  'admin' : IDL.Null,
  'visitor' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : SenderType,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SessionState = IDL.Record({
  'adminOnline' : IDL.Bool,
  'visitorOnline' : IDL.Bool,
});
export const SignalEntry = IDL.Record({
  'id' : IDL.Nat,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
  'payload' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSignals' : IDL.Func([], [], []),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Int], [IDL.Vec(ChatMessage)], ['query']),
  'getSessionState' : IDL.Func([], [SessionState], ['query']),
  'getSignals' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(SignalEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postSignal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, SenderType], [IDL.Nat], []),
  'setAdminOnline' : IDL.Func([IDL.Bool], [], []),
  'setAdminSettings' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
  'setVisitorOnline' : IDL.Func([IDL.Bool], [], []),
  'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminSettings = IDL.Record({
    'aiMode' : IDL.Bool,
    'aiVoice' : IDL.Bool,
  });
  const SenderType = IDL.Variant({
    'ai' : IDL.Null,
    'admin' : IDL.Null,
    'visitor' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : SenderType,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SessionState = IDL.Record({
    'adminOnline' : IDL.Bool,
    'visitorOnline' : IDL.Bool,
  });
  const SignalEntry = IDL.Record({
    'id' : IDL.Nat,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
    'payload' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSignals' : IDL.Func([], [], []),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Int], [IDL.Vec(ChatMessage)], ['query']),
    'getSessionState' : IDL.Func([], [SessionState], ['query']),
    'getSignals' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(SignalEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postSignal' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, SenderType], [IDL.Nat], []),
    'setAdminOnline' : IDL.Func([IDL.Bool], [], []),
    'setAdminSettings' : IDL.Func([IDL.Bool, IDL.Bool], [], []),
    'setVisitorOnline' : IDL.Func([IDL.Bool], [], []),
    'verifyAdminPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };