/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings { 'aiMode' : boolean, 'aiVoice' : boolean }
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'sender' : SenderType,
  'timestamp' : bigint,
}
export type SenderType = { 'ai' : null } |
  { 'admin' : null } |
  { 'visitor' : null };
export interface SessionState {
  'adminOnline' : boolean,
  'visitorOnline' : boolean,
}
export interface SignalEntry {
  'id' : bigint,
  'role' : string,
  'timestamp' : bigint,
  'payload' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSignals' : ActorMethod<[], undefined>,
  'getAdminSettings' : ActorMethod<[], AdminSettings>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getSessionState' : ActorMethod<[], SessionState>,
  'getSignals' : ActorMethod<[string, bigint], Array<SignalEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postSignal' : ActorMethod<[string, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, SenderType], bigint>,
  'setAdminOnline' : ActorMethod<[boolean], undefined>,
  'setAdminSettings' : ActorMethod<[boolean, boolean], undefined>,
  'setVisitorOnline' : ActorMethod<[boolean], undefined>,
  'verifyAdminPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];